compile:
	/home/alarcos/Escritorio/gcc7.2.0instalation/home/alarcos/Escritorio/gcc-7.2.0/bin/g++ 16_division-by-a-power-of-two-denominator-test2.c -o 16_division-by-a-power-of-two-denominator-test2_run -lm
run:
	./16_division-by-a-power-of-two-denominator-test2_run