CXX ?= g++
CXXFLAGS ?= -std=c++17

compile:
	$(CXX) 16_division-by-a-power-of-two-denominator-test1.c -o 16_division-by-a-power-of-two-denominator-test1_run -lm
run:
	./16_division-by-a-power-of-two-denominator-test1_run
