CXX ?= g++
CXXFLAGS ?= -std=c++17

compile:
	$(CXX) 26_invariant-if-statements-within-loops-test1.c -o 26_invariant-if-statements-within-loops-test1_run
run:
	./26_invariant-if-statements-within-loops-test1_run
