compile:
	/home/alarcos/Escritorio/gcc7.2.0instalation/home/alarcos/Escritorio/gcc-7.2.0/bin/g++ 09_dead-code-elimination-test1.c -o 09_dead-code-elimination-test1_run
run:
	./09_dead-code-elimination-test1_run