compile:
	/home/alarcos/Escritorio/gcc7.2.0instalation/home/alarcos/Escritorio/gcc-7.2.0/bin/g++ 23_chains-of-pointers-test1.c -o 23_chains-of-pointers-test1_run
run:
	./23_chains-of-pointers-test1_run