CXX ?= g++
CXXFLAGS ?= -std=c++17

compile:
	$(CXX) 33_TemporaryReturnVariableElimination-test2.c -o 33_TemporaryReturnVariableElimination-test2_run
run:
	./33_TemporaryReturnVariableElimination-test2_run
