compile:
	/home/alarcos/Escritorio/gcc7.2.0instalation/home/alarcos/Escritorio/gcc-7.2.0/bin/g++ 06_constructor-initialization-lists-test1.c -o 06_constructor-initialization-lists-test1_run
run:
	./06_constructor-initialization-lists-test1_run