compile:
	/home/alarcos/Escritorio/gcc7.2.0instalation/home/alarcos/Escritorio/gcc-7.2.0/bin/g++ 07_common-subexpression-elimination-test1.c -o 07_common-subexpression-elimination-test1_run
run:
	./07_common-subexpression-elimination-test1_run