config:
	javac Test1/test.java Test1_Xint/test.java Test2/test.java Test2_Xint/test.java test_T50.java
	java -cp . test_T50.java

end:
	rm -f Test1/*.class Test2/*.class Test1_Xint/*.class Test2_Xint/*.class *.class