compile:
	/home/alarcos/Escritorio/gcc7.2.0instalation/home/alarcos/Escritorio/gcc-7.2.0/bin/g++ 41_PointerDereference-test2.c -o 41_PointerDereference-test2_run
run:
	./41_PointerDereference-test2_run