compile:
	/home/alarcos/Escritorio/gcc7.2.0instalation/home/alarcos/Escritorio/gcc-7.2.0/bin/g++ 51_coarsening-recursion-test1.c -o 51_coarsening-recursion-test1_run
run:
	./51_coarsening-recursion-test1_run