compile:
	/home/alarcos/Escritorio/gcc7.2.0instalation/home/alarcos/Escritorio/gcc-7.2.0/bin/g++ 14_constants-inside-loops-test1.c -o 14_constants-inside-loops-test1_run
run:
	./14_constants-inside-loops-test1_run