compile:
	/home/alarcos/Escritorio/gcc7.2.0instalation/home/alarcos/Escritorio/gcc-7.2.0/bin/g++ 11_global-variables-within-loops-test1.c -o 11_global-variables-within-loops-test1_run
run:
	./11_global-variables-within-loops-test1_run