compile:
	/home/alarcos/Escritorio/gcc7.2.0instalation/home/alarcos/Escritorio/gcc-7.2.0/bin/g++ 21_passing-structures-by-reference-instead-of-value-test2.c -o 21_passing-structures-by-reference-instead-of-value-test2_run
run:
	./21_passing-structures-by-reference-instead-of-value-test2_run