CXX ?= g++
CXXFLAGS ?= -std=c++17

compile:
	$(CXX) 17_multiplication-by-a-power-of-two-factor-test1.c -o 17_multiplication-by-a-power-of-two-factor-test1_run
run:
	./17_multiplication-by-a-power-of-two-factor-test1_run
