compile:
	/home/alarcos/Escritorio/gcc7.2.0instalation/home/alarcos/Escritorio/gcc-7.2.0/bin/g++ 04_cascaded-function-calls-test1.c -o 04_cascaded-function-calls-test1_run
run:
	./04_cascaded-function-calls-test1_run