compile:
	/home/alarcos/Escritorio/gcc7.2.0instalation/home/alarcos/Escritorio/gcc-7.2.0/bin/g++ 17_multiplication-by-a-power-of-two-factor-test2.c -o 17_multiplication-by-a-power-of-two-factor-test2_run
run:
	./17_multiplication-by-a-power-of-two-factor-test2_run