compile:
	/home/alarcos/Escritorio/gcc7.2.0instalation/home/alarcos/Escritorio/gcc-7.2.0/bin/g++ 26_invariant-if-statements-within-loops-test2.c -o 26_invariant-if-statements-within-loops-test2_run
run:
	./26_invariant-if-statements-within-loops-test2_run