CXX ?= g++
CXXFLAGS ?= -std=c++17

compile:
	$(CXX) 33_TemporaryReturnVariableElimination-test1.c -o 33_TemporaryReturnVariableElimination-test1_run
run:
	./33_TemporaryReturnVariableElimination-test1_run
