compile:
	/home/alarcos/Escritorio/gcc7.2.0instalation/home/alarcos/Escritorio/gcc-7.2.0/bin/g++ 08_mapping-structures-test1.c -o 08_mapping-structures-test1_run
run:
	./08_mapping-structures-test1_run