CXX ?= g++
CXXFLAGS ?= -std=c++17

compile:
	$(CXX) 26_invariant-if-statements-within-loops-test2.c -o 26_invariant-if-statements-within-loops-test2_run
run:
	./26_invariant-if-statements-within-loops-test2_run
