compile:
	/home/alarcos/Escritorio/gcc7.2.0instalation/home/alarcos/Escritorio/gcc-7.2.0/bin/g++ 10_exception-handling-test1.c -o 10_exception-handling-test1_run
run:
	./10_exception-handling-test1_run