compile:
	/home/alarcos/Escritorio/gcc7.2.0instalation/home/alarcos/Escritorio/gcc-7.2.0/bin/g++ 15_initialization-versus-assignment-test1.c -o 15_initialization-versus-assignment-test1_run
run:
	./15_initialization-versus-assignment-test1_run