compile:
	/home/alarcos/Escritorio/gcc7.2.0instalation/home/alarcos/Escritorio/gcc-7.2.0/bin/g++ 05_row-major-accesing-test1.c -o 05_row-major-accesing-test1_run
run:
	./05_row-major-accesing-test1_run