compile:
	/home/alarcos/Escritorio/gcc7.2.0instalation/home/alarcos/Escritorio/gcc-7.2.0/bin/g++ 18_integer-versus-character-test1.c -o 18_integer-versus-character-test1_run
run:
	./18_integer-versus-character-test1_run