compile:
	/home/alarcos/Escritorio/gcc7.2.0instalation/home/alarcos/Escritorio/gcc-7.2.0/bin/g++ 33_TemporaryReturnVariableElimination-test1.c -o 33_TemporaryReturnVariableElimination-test1_run
run:
	./33_TemporaryReturnVariableElimination-test1_run