compile:
	/home/alarcos/Escritorio/gcc7.2.0instalation/home/alarcos/Escritorio/gcc-7.2.0/bin/g++ 42_VariablesDeRegistro-test2.c -o 42_VariablesDeRegistro-test2_run
run:
	./42_VariablesDeRegistro-test2_run